/*
  code is generated by jvsmg-tool (jv state machine generator)',
  file 'debugLed' generated on 2023-05-09 19:41:15
*/

// Module debugLed

// --- Setup -----------

void debugledSetup() {
  pinMode(LED_BUILTIN, OUTPUT);
}        

// --- Commands -----------

void debugledOff() {
  digitalWrite(LED_BUILTIN, LOW);
}

void debugledOn() {
  digitalWrite(LED_BUILTIN, HIGH);
}

