/*
  code is generated by jvsmg-tool (jv state machine generator)',
  file 'debugLed' generated on 2023-05-09 19:41:15
*/

// Module debugLed

// --- Setup -----------

void debugledSetup() {
  // TODO: custom initialization
}        

// --- Commands -----------

void debugledOff() {
  // TODO: implement command 'off'
}

void debugledOn() {
  // TODO: implement command 'on'
}

