/*
  code is generated by jvsmg-tool (jv state machine generator)',
  file 'the-jv-display' generated on 2023-05-09 19:41:15
*/

void setup() {
  Serial.begin(115200);

  thejvdisplaySetup();
  debugledSetup();
  imageSetup();
}

void loop() {
  thejvdisplayLoop();
}
